# --- Finalized _config.yml for Minimal Theme ---

# 1. Define the theme (Built-in Jekyll theme)
theme: minimal 

# 2. SET MAIN SITE HEADER (This should now be your Name/Title)
title: Joël Mongeon

# 3. Site Metadata
description: PhD Researcher focusing on Supply Chain Optimization, Resilience, and Sustainability.
baseurl: "" # Keep this blank for root domain deployment
url: "https://jmongeon08.github.io" 
