# --- Theme Configuration ---

# 1. Define the theme (Minimal)
remote_theme: "academicpages/academicpages.github.io@v6.0.0"
plugins:
  - jekyll-remote-theme

# 2. SET MAIN SITE HEADER (This will be the largest text at the top)
title: About

# 3. Site Metadata
description: PhD Researcher focusing on Supply Chain Optimization, Resilience, and Sustainability.
baseurl: ""
url: "https://jmongeon08.github.io"
